services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - traefik-proxy

  traefik:
    image: traefik:v3.4
    ports:
      - "80:80"
      - "8080:8080"
      - "25565:25565"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./data/certs:/var/traefik/certs/:rw
    networks:
      - traefik-proxy
